version: "3.8"

services:
  app:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "80:3001"

volumes:
  uptime-kuma:
    driver: local